[package]
name = "verify_password"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5"
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"

[lib]
name = "verify_password"
path = "verify_password.rs"
crate-type = ["cdylib"]